export const Industries = [
"Offices of Real Estate Agents and Brokers",
"Drinking Places (Alcoholic Beverages)",
"Car Washes",
"Commercial Lithographic Printing",
"Automotive Body, Paint, and Interior Repair and Maintenance",
"Gift, Novelty, and Souvenir Stores",
"Other Services Related to Advertising",
"Commercial and Institutional Building Construction",
"All Other Health and Personal Care Stores",
"Snack and Nonalcoholic Beverage Bars",
"Used Car Dealers",
"Offices of Certified Public Accountants",
"Automotive Oil Change and Lubrication Shops",
"Other Commercial Printing",
"Offices of Lawyers",
"Tax Preparation Services",
"Metal Coating, Engraving (except Jewelry and Silverware), and Allied S",
"Offices of Physicians (except Mental Health Specialists)",
"Automotive Parts and Accessories Stores",
"Other Apparel Accessories and Other Apparel Manufacturing",
"Nail Salons",
"Beauty Salons",
"Coin-Operated Laundries and Drycleaners",
"Gasoline Stations with Convenience Stores",
"Residential Remodelers",
"Local Messengers and Local Delivery",
"Other Residential Care Facilities",
"Computer Training",
"Construction, Mining, and Forestry Machinery and Equipment Rental and",
"Ice Manufacturing",
"Other Miscellaneous Durable Goods Merchant Wholesalers",
"Recreational Vehicle Dealers",
"Supermarkets and Other Grocery (except Convenience) Stores",
"All Other Personal Services",
"Commercial Screen Printing",
"Other Activities Related to Real Estate",
"Carpet and Upholstery Cleaning Services",
"Electrical Contractors",
"Child Day Care Services",
"Limited-Service Restaurants",
"Full-Service Restaurants",
"Offices of Physical, Occupational and Speech Therapists, and Audiologi",
"Medical Laboratories",
"Offices of All Other Miscellaneous Health Practitioners",
"Women's Clothing Stores",
"Solid Waste Collection",
"Wine and Distilled Alcoholic Beverage Merchant Wholesalers",
"All Other Amusement and Recreation Industries",
"Other Accounting Services",
"All Other Plastics Product Manufacturing",
"Veterinary Services",
"Other Personal Care Services",
"Sign Manufacturing",
"Hotels (except Casino Hotels) and Motels",
"Offices of Chiropractors",
"Recreational and Vacation Camps (except Campgrounds)",
"Motor Vehicle Supplies and New Parts Merchant Wholesalers",
"Advertising Agencies",
"Computer and Office Machine Repair and Maintenance",
"Plumbing, Heating, and Air-Conditioning Contractors",
"Other Miscellaneous Nondurable Goods Merchant Wholesalers",
"Florists",
"Business Associations",
"General Automotive Repair",
"Public Relations Agencies",
"Support Activities for Oil and Gas Operations",
"Other Business Service Centers (including Copy Shops)",
"Architectural Services",
"Other Metalworking Machinery Manufacturing",
"Masonry Contractors",
"Engineering Services",
"Portfolio Management",
"All Other Miscellaneous Wood Product Manufacturing",
"Nursery and Tree Production",
"Site Preparation Contractors",
"Machine Shops",
"Administrative Management and General Management Consulting Services",
"Electronic Shopping",
"All Other Specialty Trade Contractors",
"Finish Carpentry Contractors",
"All Other Professional, Scientific, and Technical Services",
"Logging",
"Automotive Glass Replacement Shops",
"General Freight Trucking, Long Distance, Truckload",
"Insurance Agencies and Brokerages",
"Cemeteries and Crematories",
"Game, Toy, and Children's Vehicle Manufacturing",
"Finfish Farming and Fish Hatcheries",
"Other Community Housing Services",
"Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesal",
"Industrial Machinery and Equipment Merchant Wholesalers",
"All Other Miscellaneous Store Retailers (except Tobacco Stores)",
"Motor Vehicle Towing",
"Investment Advice",
"Cafeterias",
"Painting and Wall Covering Contractors",
"Other Direct Selling Establishments",
"Recyclable Material Merchant Wholesalers",
"Sports and Recreation Instruction",
"Computer and Software Stores",
"Clothing Accessories Stores",
"Septic Tank and Related Services",
"Broilers and Other Meat Type",
"Pet and Pet Supplies Stores",
"New Housing Operative Builders",
"Other Scientific and Technical Consulting Services",
"Remediation Services",
"Other Management Consulting Services",
"Other Individual and Family Services",
"Home Health Care Services",
"Used Household and Office Goods Moving",
"All Other Miscellaneous Waste Management Services",
"Nonupholstered Wood Household Furniture Manufacturing",
"Fish and Seafood Merchant Wholesalers",
"Construction Sand and Gravel Mining",
"Offices of Physicians, Mental Health Specialists",
"Other Fabricated Wire Product Manufacturing",
"All Other Outpatient Care Centers",
"All Other Information Services",
"Electronic Auctions",
"All Other Industrial Machinery Manufacturing",
"Dried and Dehydrated Food Manufacturing",
"All Other Miscellaneous Ambulatory Health Care Services",
"Exam Preparation and Tutoring",
"New Car Dealers",
"Graphic Design Services",
"Convenience Stores",
"Lessors of Nonresidential Buildings (except Miniwarehouses)",
"Process, Physical Distribution, and Logistics Consulting Services",
"Landscaping Services",
"Interior Design Services",
"Books Printing",
"Machine Tool (Metal Forming Types) Manufacturing",
"Homes for the Elderly",
"Wood Kitchen Cabinet and Countertop Manufacturing",
"Poultry Hatcheries",
"All Other General Merchandise Stores",
"Psychiatric and Substance Abuse Hospitals",
"Fabricated Structural Metal Manufacturing",
"Flooring Contractors",
"Security Guards and Patrol Services",
"Transportation Equipment and Supplies (except Motor Vehicle) Merchant",
"Funeral Homes and Funeral Services",
"Offices of Dentists",
"Charter Bus Industry",
"Specialized Freight (except Used Goods) Trucking, Local",
"Commercial and Industrial Machinery and Equipment (except Automotive a",
"Display Advertising",
"Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Sta",
"Other Building Material Dealers",
"Pet Care (except Veterinary) Services",
"Furniture Merchant Wholesalers",
"Photography Studios, Portrait",
"All Other Support Activities for Transportation",
"Sheet Metal Work Manufacturing",
"Computer Systems Design Services",
"Automobile and Other Motor Vehicle Merchant Wholesalers",
"Food (Health) Supplement Stores",
"Other Support Activities for Air Transportation",
"Offices of Optometrists",
"All Other Specialty Food Stores",
"Other Commercial and Industrial Machinery and Equipment Rental and Lea",
"Dental Laboratories",
"Video Tape and Disc Rental",
"Other Support Activities for Road Transportation",
"Lessors of Residential Buildingsv and Dwellings",
"Testing Laboratories",
"Freight Transportation Arrangement",
"Direct Mail Advertising",
"Breweries",
"Pharmacies and Drug Stores",
"Metal Service Centers and Other Metal Merchant Wholesalers",
"Frozen Specialty Food Manufacturing",
"Other Building Equipment Contractors",
"New Single-Family Housing Construction (except Operative Builders)",
"Commercial Bakeries",
"General Freight Trucking, Local",
"Teleproduction and Other Postproduction Services",
"Fitness and Recreational Sports Centers",
"Cosmetics, Beauty Supplies, and Perfume Stores",
"Couriers",
"Drycleaning and Laundry Services (except Coin-Operated)",
"Sporting Goods Stores",
"Private Mail Centers",
"Folding Paperboard Box Manufacturing",
"Trust, Fiduciary, and Custody Activities",
"Specialty (except Psychiatric and Substance Abuse) Hospitals",
"Book Publishers",
"All Other Telecommunications",
"Highway, Street, and Bridge Construction",
"Automobile Driving Schools",
"Other Performing Arts Companies",
"Environmental Consulting Services",
"Janitorial Services",
"Other Waste Collection",
"Custom Computer Programming Services",
"Radio, Television, and Other Electronics Stores",
"Employment Placement Agencies",
"Wood Window and Door Manufacturing",
"Wood Container and Pallet Manufacturing",
"Musical Instrument and Supplies Stores",
"Ready-Mix Concrete Manufacturing",
"Residential Mental Retardation Facilities",
"Support Activities for Animal Production",
"Automobile Manufacturing",
"Drugs and Druggists' Sundries Merchant Wholesalers",
"Furniture Stores",
"Other Grocery and Related Products Merchant Wholesalers",
"Services for the Elderly and Persons with Disabilities",
"Flour Mixes and Dough Manufacturing",
"Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers",
"Book Stores",
"Other Services to Buildings and Dwellings",
"Flavoring Syrup and Concentrate Manufacturing",
"Other Personal and Household Goods Repair and Maintenance",
"Spring (Heavy Gauge) Manufacturing",
"Educational Support Services",
"Welding and Soldering Equipment Manufacturing",
"Other Millwork (including Flooring)",
"Financial Transactions Processing, Reserve, and Clearinghouse Activiti",
"Beer, Wine, and Liquor Stores",
"Kitchen Utensil, Pot, and Pan Manufacturing",
"Retail Bakeries",
"Shoe Stores",
"Promoters of Performing Arts, Sports, and Similar Events without Facil",
"Men's Clothing Stores",
"All Other Miscellaneous Food Manufacturing",
"Spice and Extract Manufacturing",
"Radio Stations",
"Special Die and Tool, Die Set, Jig, and Fixture Manufacturing",
"Sewing, Needlework, and Piece Goods Stores",
"Other Warehousing and Storage",
"Temporary Help Services",
"Jewelry Stores",
"Security Systems Services (except Locksmiths)",
"Iron and Steel Forging",
"Packaging and Labeling Services",
"Outpatient Mental Health and Substance Abuse Centers",
"Children's and Infants' Clothing Stores",
"Heating Oil Dealers",
"Radio and Television Broadcasting and Wireless Communications Equipmen",
"Institutional Furniture Manufacturing",
"All Other Miscellaneous Schools and Instruction",
"Other Commercial Equipment Merchant Wholesalers",
"Vending Machine Operators",
"Marketing Consulting Services",
"Drywall and Insulation Contractors",
"Barber Shops",
"All Other Miscellaneous Manufacturing",
"Packaged Frozen Food Merchant Wholesalers",
"Linen Supply",
"Other Nonhazardous Waste Treatment and Disposal",
"Wholesale Trade Agents and Brokers",
"Office Administrative Services",
"Home Centers",
"Refrigeration Equipment and Supplies Merchant Wholesalers",
"Chocolate and Confectionery Manufacturing from Cacao Beans",
"All Other Automotive Repair and Maintenance",
"Stationery and Office Supplies Merchant Wholesalers",
"Nursery and Garden Centers",
"Landscape Architectural Services",
"Caterers",
"Surgical Appliance and Supplies Manufacturing",
"Other Automotive Mechanical and Electrical Repair and Maintenance",
"Fine Arts Schools",
"Construction and Mining (except Oil Well) Machinery and Equipment Merc",
"Diagnostic Imaging Centers",
"Service Establishment Equipment and Supplies Merchant Wholesalers",
"Other Computer Related Services",
"",
"Water and Sewer Line and Related Structures Construction",
"Prefabricated Metal Building and Component Manufacturing",
"Research and Development in the Social Sciences and Humanities",
"Navigational Services to Shipping",
"All Other Miscellaneous Chemical Product and Preparation Manufacturing",
"Floriculture Production",
"Internet Publishing and Broadcasting",
"Other Foundation, Structure, and Building Exterior Contractors",
"Marketing Research and Public Opinion Polling",
"Prepress Services",
"Independent Artists, Writers, and Performers",
"Meat Markets",
"Nonscheduled Chartered Freight Air Transportation",
"Hardware Manufacturing",
"Custom Architectural Woodwork and Millwork Manufacturing",
"All Other Transit and Ground Passenger Transportation",
"Direct Health and Medical Insurance Carriers",
"Women's, Children's, and Infants' Clothing and Accessories Merchant Wh",
"Television Broadcasting",
"Exterminating and Pest Control Services",
"Plastics Materials and Basic Forms and Shapes Merchant Wholesalers",
"Commercial, Industrial, and Institutional Electric Lighting Fixture Ma",
"Tile and Terrazzo Contractors",
"Hardware Merchant Wholesalers",
"Bare Printed Circuit Board Manufacturing",
"Envelope Manufacturing",
"Bowling Centers",
"Semiconductor and Related Device Manufacturing",
"Other Building Finishing Contractors",
"Air Purification Equipment Manufacturing",
"Elementary and Secondary Schools",
"Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant",
"Audio and Video Equipment Manufacturing",
"Automotive Exhaust System Repair",
"Mushroom Production",
"Plastics Pipe and Pipe Fitting Manufacturing",
"Office Machinery and Equipment Rental and Leasing",
"Freestanding Ambulatory Surgical and Emergency Centers",
"Iron Foundries",
"Confectionery Merchant Wholesalers",
"Cosmetology and Barber Schools",
"Motorcycle Dealers",
"Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers",
"Water Supply and Irrigation Systems",
"All Other Miscellaneous Fabricated Metal Product Manufacturing",
"Fish and Seafood Markets",
"Adhesive Manufacturing",
"Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers",
"Grain and Field Bean Merchant Wholesalers",
"Office Supplies and Stationery",
"Special Needs Transportation",
"Optical Goods Stores",
"Petroleum Lubricating Oil and Grease Manufacturing",
"All Other Motor Vehicle Dealers",
"Family Clothing Stores",
"Motor Vehicle Transmission and Power Train Parts Manufacturing",
"Other Clothing Stores",
"Direct Title Insurance Carriers",
"Tour Operators",
"Other Heavy and Civil Engineering Construction",
"Offices of Real Estate Appraisers",
"All Other Home Furnishings Stores",
"Carbon and Graphite Product Manufacturing",
"Poultry Processing",
"Electroplating, Plating, Polishing, Anodizing, and Coloring",
"Ambulance Services",
"Direct Property and Casualty Insurance Carriers",
"Museums",
"Collection Agencies",
"Luggage and Leather Goods Stores",
"Hobby, Toy, and Game Stores",
"Glass and Glazing Contractors",
"Other Specialized Design Services",
"Outdoor Power Equipment Stores",
"Motion Picture and Video Production",
"Roofing Contractors",
"Oil and Gas Pipeline and Related Structures Construction",
"All Other Basic Organic Chemical Manufacturing",
"Travel Agencies",
"All Other Animal Production",
"Dental Equipment and Supplies Manufacturing",
"Department Stores (except Discount Department Stores)",
"Offices of Mental Health Practitioners (except Physicians)",
"Costume Jewelry and Novelty Manufacturing",
"All Other Support Services",
"Limousine Service",
"Household Appliance Stores",
"Newspaper Publishers",
"Colleges, Universities, and Professional Schools",
"Professional and Management Development Training",
"Commercial Flexographic Printing",
"Poultry and Poultry Product Merchant Wholesalers",
"Bed-and-Breakfast Inns",
"Bolt, Nut, Screw, Rivet, and Washer Manufacturing",
"Brick, Stone, and Related Construction Material Merchant Wholesalers",
"Home and Garden Equipment Repair and Maintenance",
"Scenic and Sightseeing Transportation, Land",
"Appliance Repair and Maintenance",
"Narrow Fabric Mills",
"Investigation Services",
"Private Households",
"Fruit and Vegetable Markets",
"Poured Concrete Foundation and Structure Contractors",
"Sound Recording Studios",
"Refrigerated Warehousing and Storage",
"Other Electronic Component Manufacturing",
"Data Processing, Hosting, and Related Services",
"All Other Miscellaneous Textile Product Mills",
"Other Snack Food Manufacturing",
"Dairy Cattle and Milk Production",
"Used Merchandise Stores",
"Surveying and Mapping (except Geophysical) Services",
"Sporting and Athletic Goods Manufacturing",
"Trusts, Estates, and Agency Accounts",
"Food Service Contractors",
"Offices of Podiatrists",
"General Line Grocery Merchant Wholesalers",
"Other Technical and Trade Schools",
"All Other Grain Farming",
"Footwear Merchant Wholesalers",
"Nursing Care Facilities",
"Motion Picture Theaters (except Drive-Ins)",
"Industrial Supplies Merchant Wholesalers",
"Hardware Stores",
"Sawmills",
"All Other Business Support Services",
"Amusement and Theme Parks",
"Direct Life Insurance Carriers",
"Geophysical Surveying and Mapping Services",
"Baked Goods Stores",
"General Rental Centers",
"Small Arms Manufacturing",
"Packing and Crating",
"All Other Travel Arrangement and Reservation Services",
"Window Treatment Stores",
"Printing and Writing Paper Merchant Wholesalers",
"Residential Property Managers",
"Printing Ink Manufacturing",
"Plate Work Manufacturing",
"Mail-Order Houses",
"Floor Covering Stores",
"Beer and Ale Merchant Wholesalers",
"Mortgage and Nonmortgage Loan Brokers",
"Nitrogenous Fertilizer Manufacturing",
"Toy and Hobby Goods and Supplies Merchant Wholesalers",
"Other Farm Product Raw Material Merchant Wholesalers",
"Industrial and Personal Service Paper Merchant Wholesalers",
"Telemarketing Bureaus",
"Precision Turned Product Manufacturing",
"Facilities Support Services",
"Quick Printing",
"Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesaler",
"Postal Service",
"Communication Equipment Repair and Maintenance",
"Art Dealers",
"Carpet and Rug Mills",
"Other Electronic Parts and Equipment Merchant Wholesalers",
"Tobacco Stores",
"Machine Tool (Metal Cutting Types) Manufacturing",
"Nonresidential Property Managers",
"Other Aircraft Parts and Auxiliary Equipment Manufacturing",
"Construction Machinery Manufacturing",
"General Warehousing and Storage",
"All Other Publishers",
"Flight Training",
"Metal Heat Treating",
"Wineries",
"Plastics Bottle Manufacturing",
"Electrical Apparatus and Equipment, Wiring Supplies, and Related Equip",
"Finfish Fishing",
"Sawmill and Woodworking Machinery Manufacturing",
"Continuing Care Retirement Communities",
"Metal Stamping",
"Sporting and Recreational Goods and Supplies Merchant Wholesalers",
"Perishable Prepared Food Manufacturing",
"General Freight Trucking, Long-Distance, Less Than Truckload",
"Record Production",
"Specialized Freight (except Used Goods) Trucking, Long-Distance",
"Surgical and Medical Instrument Manufacturing",
"Fabricated Pipe and Pipe Fitting Manufacturing",
"Soil Preparation, Planting, and Cultivating",
"Other Lighting Equipment Manufacturing",
"Meat Processed from Carcasses",
"Nonchocolate Confectionery Manufacturing",
"Industrial Mold Manufacturing",
"Office Machinery Manufacturing",
"Analytical Laboratory Instrument Manufacturing",
"Building Inspection Services",
"Mobile Food Services",
"All Other Transportation Equipment Manufacturing",
"Prerecorded Tape, Compact Disc, and Record Stores",
"Claims Adjusting",
"All Other Legal Services",
"Other Concrete Product Manufacturing",
"Metal Window and Door Manufacturing",
"Title Abstract and Settlement Offices",
"All Other Consumer Goods Rental",
"International Trade Financing",
"Taxi Service",
"Jewelry (except Costume) Manufacturing",
"Promoters of Performing Arts, Sports, and Similar Events with Faciliti",
"Periodical Publishers",
"Amusement Arcades",
"Power and Communication Line and Related Structures Construction",
"Fresh Fruit and Vegetable Merchant Wholesalers",
"Business to Business Electronic Markets",
"Computer and Computer Peripheral Equipment and Software Merchant Whole",
"Cutting Tool and Machine Tool Accessory Manufacturing",
"Other Chemical and Allied Products Merchant Wholesalers",
"Musical Instrument Manufacturing",
"Consumer Electronics Repair and Maintenance",
"Bottled Water Manufacturing",
"Truck Trailer Manufacturing",
"Tobacco Stemming and Redrying",
"Industrial Valve Manufacturing",
"Lessors of Other Real Estate Property",
"Industrial Building Construction",
"Commercial Photography",
"New Multifamily Housing Construction (except Operative Builders)",
"All Other Insurance Related Activities",
"Truss Manufacturing",
"Passenger Car Rental",
"Packaging Machinery Manufacturing",
"Confectionery and Nut Stores",
"Other Measuring and Controlling Device Manufacturing",
"Men's and Boys' Cut and Sew Suit, Coat, and Overcoat Manufacturing",
"Heavy Duty Truck Manufacturing",
"Residential Electric Lighting Fixture Manufacturing",
"Roofing, Siding, and Insulation Material Merchant Wholesalers",
"Wireless Telecommunications Carriers (except Satellite)",
"Ornamental and Architectural Metal Work Manufacturing",
"Manufactured (Mobile) Home Dealers",
"Industrial Design Services",
"Software Publishers",
"Petroleum Bulk Stations and Terminals",
"Specialty Canning",
"Other Motion Picture and Video Industries",
"All Other Miscellaneous Electrical Equipment and Component Manufacturi",
"Industrial Launderers",
"Other Electronic and Precision Equipment Repair and Maintenance",
"Boat Dealers",
"Other Commercial and Service Industry Machinery Manufacturing",
"Pesticide and Other Agricultural Chemical Manufacturing",
"Diet and Weight Reducing Centers",
"Apiculture",
"Farm and Garden Machinery and Equipment Merchant Wholesalers",
"Child and Youth Services",
"Human Resources and Executive Search Consulting Services",
"Home Health Equipment Rental",
"Payroll Services",
"Skiing Facilities",
"Employee Leasing Services",
"Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Whole",
"All Other Motor Vehicle Parts Manufacturing",
"Other Gasoline Stations",
"Support Activities for Forestry",
"Crown and Closure Manufacturing",
"Mining Machinery and Equipment Manufacturing",
"Tire Dealers",
"Parking Lots and Garages",
"Hazardous Waste Collection",
"Outerwear Knitting Mills",
"Sports Teams and Clubs",
"Internet Publishing and Broadcasting and Web Search Portals",
"Agents and Managers for Artists, Athletes, Entertainers, and Other Pub",
"Photographic and Photocopying Equipment Manufacturing",
"Research and Development in Biotechnology",
"Paint and Coating Manufacturing",
"Third Party Administration of Insurance and Pension Funds",
"Plastics and Rubber Industry Machinery Manufacturing",
"Elevator and Moving Stairway Manufacturing",
"Convention and Trade Show Organizers",
"Marinas",
"Formal Wear and Costume Rental",
"Siding Contractors",
"Other Professional Equipment and Supplies Merchant Wholesalers",
"Recreational Goods Rental",
"Medicinal and Botanical Manufacturing",
"Upholstered Household Furniture Manufacturing",
"All Other Converted Paper Product Manufacturing",
"Chicken Egg Production",
"Unsupported Plastics Packaging Film and Sheet Manufacturing",
"Schiffli Machine Embroidery",
"All Other Cut and Sew Apparel Manufacturing",
"Other Computer Peripheral Equipment Manufacturing",
"Meat and Meat Product Merchant Wholesalers",
"Electronic Computer Manufacturing",
"Racetracks",
"Ceramic Wall and Floor Tile Manufacturing",
"Other Direct Insurance (except Life, Health, and Medical) Carriers",
"Turkey Production",
"Document Preparation Services",
"Community Food Services",
"Camera and Photographic Supplies Stores",
"Iron and Steel Pipe and Tube Manufacturing from Purchased Steel",
"Fiber Can, Tube, Drum, and Similar Products Manufacturing",
"Shellfish Fishing",
"Farm Machinery and Equipment Manufacturing",
"Fruit and Vegetable Canning",
"Framing Contractors",
"Other Animal Food Manufacturing",
"Inorganic Dye and Pigment Manufacturing",
"Men's and Boys' Clothing and Furnishings Merchant Wholesalers",
"Motor and Generator Manufacturing",
"Toilet Preparation Manufacturing",
"Automotive Transmission Repair",
"Powder Metallurgy Part Manufacturing",
"Sales Financing",
"Wired Telecommunications Carriers",
"RV (Recreational Vehicle) Parks and Campgrounds",
"Tradebinding and Related Work",
"Leather and Hide Tanning and Finishing",
"Textile Bag Mills",
"Other Construction Material Merchant Wholesalers",
"Computer Facilities Management Services",
"Media Representatives",
"Prefabricated Wood Building Manufacturing",
"Sanitary Paper Product Manufacturing",
"Pharmaceutical Preparation Manufacturing",
"Instrument Manufacturing for Measuring and Testing Electricity and Ele",
"Rooming and Boarding Houses",
"Coffee and Tea Manufacturing",
"Materials Recovery Facilities",
"Home Furnishing Merchant Wholesalers",
"Cheese Manufacturing",
"Plastics Material and Resin Manufacturing",
"Commercial Gravure Printing",
"Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasi",
"Carburetor, Piston, Piston Ring, and Valve Manufacturing",
"Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing",
"Primary Aluminum Production",
"Reupholstery and Furniture Repair",
"Bus and Other Motor Vehicle Transit Systems",
"All Other Traveler Accommodation",
"Advertising Material Distribution Services",
"HMO Medical Centers",
"Drilling Oil and Gas Wells",
"Polish and Other Sanitation Good Manufacturing",
"Other Vegetable (except Potato) and Melon Farming",
"Gasket, Packing, and Sealing Device Manufacturing",
"Animal (except Poultry) Slaughtering",
"Farm Supplies Merchant Wholesalers",
"Goat Farming",
"Paint and Wallpaper Stores",
"Dairy Product (except Dried or Canned) Merchant Wholesalers",
"Other Airport Operations",
"Conveyor and Conveying Equipment Manufacturing",
"Hazardous Waste Treatment and Disposal",
"School and Employee Bus Transportation",
"Commercial Air, Rail, and Water Transportation Equipment Rental and Le",
"Hardwood Veneer and Plywood Manufacturing",
"Ophthalmic Goods Manufacturing",
"Fluid Power Pump and Motor Manufacturing",
"Broadwoven Fabric Finishing Mills",
"Turbine and Turbine Generator Set Units Manufacturing",
"Consumer Electronics and Appliances Rental",
"Structural Steel and Precast Concrete Contractors",
"Fluid Power Valve and Hose Fitting Manufacturing",
"Other Food Crops Grown Under Cover",
"Stationery, Tablet, and Related Product Manufacturing",
"Drafting Services",
"Relay and Industrial Control Manufacturing",
"Paint, Varnish, and Supplies Merchant Wholesalers",
"Burial Casket Manufacturing",
"Scenic and Sightseeing Transportation, Other",
"Instruments and Related Products Manufacturing for Measuring, Displayi",
"Automatic Vending Machine Manufacturing",
"Translation and Interpretation Services",
"Telephone Answering Services",
"Corrugated and Solid Fiber Box Manufacturing",
"Scenic and Sightseeing Transportation, Water",
"Forest Nurseries and Gathering of Forest Products",
"Electrical and Electronic Appliance, Television, and Radio Set Merchan",
"All Other Miscellaneous General Purpose Machinery Manufacturing",
"Steel Wire Drawing",
"Men's and Boys' Cut and Sew Other Outerwear Manufacturing",
"Air-Conditioning and Warm Air Heating Equipment and Commercial and Ind",
"Food Product Machinery Manufacturing",
"Other Financial Vehicles",
"Showcase, Partition, Shelving, and Locker Manufacturing",
"All Other Miscellaneous Nonmetallic Mineral Product Manufacturing",
"Digital Printing",
"Hand and Edge Tool Manufacturing",
"Residential Mental Health and Substance Abuse Facilities",
"Other Communications Equipment Manufacturing",
"Other Fuel Dealers",
"Motor Vehicle Steering and Suspension Components (except Spring) Manuf",
"Men's and Boys' Cut and Sew Work Clothing Manufacturing",
"Farm Product Warehousing and Storage",
"All Other Rubber Product Manufacturing",
"Concrete Pipe Manufacturing",
"Women's and Girls' Cut and Sew Lingerie, Loungewear, and Nightwear Man",
"Aluminum Die-Casting Foundries",
"Commercial Laundry, Drycleaning, and Pressing Machine Manufacturing",
"Automatic Environmental Control Manufacturing for Residential, Commerc",
"Aluminum Extruded Product Manufacturing",
"Deep Sea Freight Transportation",
"Nonferrous Forging",
"Boat Building",
"Nonscheduled Chartered Passenger Air Transportation",
"Cable and Other Subscription Programming",
"Land Subdivision",
"Other Spectator Sports",
"Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturi",
"Saw Blade and Handsaw Manufacturing",
"Other Tobacco Product Manufacturing",
"Plastics, Foil, and Coated Paper Bag Manufacturing",
"Custom Compounding of Purchased Resins",
"General Medical and Surgical Hospitals",
"Motor Vehicle Parts (Used) Merchant Wholesalers",
"Coated and Laminated Packaging Paper and Plastics Film Manufacturing",
"Petrochemical Manufacturing",
"Ball and Roller Bearing Manufacturing",
"Other Electric Power Generation",
"All Other Nondepository Credit Intermediation",
"Other Crushed and Broken Stone Mining and Quarrying",
"Locksmiths",
"Other Support Activities for Water Transportation",
"Offices of Other Holding Companies",
"Polystyrene Foam Product Manufacturing",
"Textile Machinery Manufacturing",
"Cut Stone and Stone Product Manufacturing",
"Book, Periodical, and Newspaper Merchant Wholesalers",
"Pump and Pumping Equipment Manufacturing",
"Power, Distribution, and Specialty Transformer Manufacturing",
"Fluid Milk Manufacturing",
"Distilleries",
"Other Nonscheduled Air Transportation",
"Language Schools",
"Gasoline Engine and Engine Parts Manufacturing",
"Electric Power Distribution",
"Ice Cream and Frozen Dessert Manufacturing",
"Computer Storage Device Manufacturing",
"Roasted Nuts and Peanut Butter Manufacturing",
"Miscellaneous Financial Investment Activities",
"Research and Development in the Physical, Engineering, and Life Scienc",
"Office Equipment Merchant Wholesalers",
"Other Social Advocacy Organizations",
"Ophthalmic Goods Merchant Wholesalers",
"Hog and Pig Farming",
"Web Search Portals",
"Ship Building and Repairing",
"Aluminum Foundries (except Die-Casting)",
"Tire Retreading",
"Kidney Dialysis Centers",
"Natural Gas Distribution",
"Postharvest Crop Activities (except Cotton Ginning)",
"Other Activities Related to Credit Intermediation",
"Canvas and Related Product Mills",
"Cut Stock, Resawing Lumber, and Planning",
"Tortilla Manufacturing",
"All Other Miscellaneous Crop Farming",
"Men's and Boys' Cut and Sew Shirt (except Work Shirt) Manufacturing",
"Concrete Block and Brick Manufacturing",
"Metal Tank (Heavy Gauge) Manufacturing",
"Software Reproducing",
"Steam and Air-Conditioning Supply",
"Golf Courses and Country Clubs",
"Administration of General Economic Programs",
"Warehouse Clubs and Superstores",
"News Dealers and Newsstands",
"Dance Companies",
"Other Marine Fishing",
"Telecommunications Resellers",
"Women's Handbag and Purse Manufacturing",
"Luggage Manufacturing",
"Coated and Laminated Paper Manufacturing",
"Women's and Girls' Cut and Sew Dress Manufacturing",
"Rubber Product Manufacturing for Mechanical Use",
"Commodity Contracts Dealing",
"Asphalt Paving Mixture and Block Manufacturing",
"Livestock Merchant Wholesalers",
"Vocational Rehabilitation Services",
"Theater Companies and Dinner Theaters",
"Photofinishing Laboratories (except One-Hour)",
"Resilient Floor Covering Manufacturing",
"Armored Car Services",
"Court Reporting and Stenotype Services",
"Telephone Apparatus Manufacturing",
"All Other Leather Good Manufacturing",
"Musical Groups and Artists",
"Asphalt Shingle and Coating Materials Manufacturing",
"Curtain and Drapery Mills",
"Glass Container Manufacturing",
"Music Publishers",
"Motorcycle, Bicycle, and Parts Manufacturing",
"Watch, Clock, and Part Manufacturing",
"Motor Vehicle Body Manufacturing",
"Aircraft Manufacturing",
"Fluid Power Cylinder and Actuator Manufacturing",
"Electric Lamp Bulb and Part Manufacturing",
"Oil and Gas Field Machinery and Equipment Manufacturing",
"Cookie and Cracker Manufacturing",
"Industrial Pattern Manufacturing",
"Women's, Girls', and Infants' Cut and Sew Apparel Contractors",
"Glass Product Manufacturing Made of Purchased Glass",
"Unsupported Plastics Profile Shapes Manufacturing",
"Thread Mills",
"Lessors of Miniwarehouses and Self-Storage Units",
"Other Poultry Production",
"Vitreous China, Fine Earthenware, and Other Pottery Manufacturing",
"Fertilizer (Mixing Only) Manufacturing",
"Fresh and Frozen Seafood Processing",
"Frozen Fruit, Juice, and Vegetable Manufacturing",
"Primary Smelting and Refining of Nonferrous Metal (except Copper and A",
"Soft Drink Manufacturing",
"Men's and Boys' Cut and Sew Apparel Contractors",
"Liquefied Petroleum Gas (Bottled Gas) Dealers",
"Dog and Cat Food Manufacturing",
"Inland Water Passenger Water Transportation",
"Crude Petroleum and Natural Gas",
"Deep Sea Passenger Transportation",
"Manifold Business Forms Printing",
"Motion Picture and Video Distribution",
"Yarn Spinning Mills",
"Database and Directory Publishers",
"Electromedical and Electrotherapeutic Apparatus Manufacturing",
"Satellite Telecommunications",
"Other Telecommunications",
"Infants' Cut and Sew Apparel Manufacturing",
"Farm Management Services",
"Travel Trailer and Camper Manufacturing",
"Other Aluminum Rolling and Drawing",
"Paper (except Newsprint) Mills",
"Small Arms Ammunition Manufacturing",
"Crushed and Broken Limestone Mining",
"Flat Glass Manufacturing",
"Heating Equipment (except Warm Air Furnaces) Manufacturing",
"Rendering and Meat Byproduct Processing",
"Apparel Accessories and Other Apparel Manufacturing",
"Blind and Shade Manufacturing",
"All Other Petroleum and Coal Products Manufacturing",
"Printing Machinery and Equipment Manufacturing",
"Repossession Services",
"Soybean Farming",
"Other Household Textile Product Mills",
"Motor Vehicle Seating and Interior Trim Manufacturing",
"Nonfolding Sanitary Food Container Manufacturing",
"Executive Search Services",
"Confectionery Manufacturing from Purchased Chocolate",
"Beef Cattle Ranching and Farming",
"Interurban and Rural Bus Transportation",
"Women's and Girls' Cut and Sew Other Outerwear Manufacturing",
"Horse and Other Equine Production",
"Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
"Soap and Other Detergent Manufacturing",
"Other Metal Container Manufacturing",
"Wood Preservation",
"Bituminous Coal Underground Mining",
"Plastics Materials and Basic Forms and Shapes Wholesalers",
"Consumer Lending",
"Professional Organizations",
"Seafood Product Preparation and Packaging",
"Rolled Steel Shape Manufacturing",
"Broadwoven Fabric Mills",
"Cutlery and Flatware (except Precious) Manufacturing",
"Apprenticeship Training",
"Fur-Bearing Animal and Rabbit",
"Investment Banking and Securities Dealing",
"Footwear and Leather Goods Repair",
"Secondary Smelting, Refining, and Alloying of Copper",
"Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Ex",
"Lead Pencil and Art Good Manufacturing",
"Other Motor Vehicle Electrical and Electronic Equipment Manufacturing",
"Tobacco and Tobacco Product Merchant Wholesalers",
"Aircraft Engine and Engine Parts Manufacturing",
"Other Metal Valve and Pipe Fitting Manufacturing",
"Manufactured Home (Mobile Home) Manufacturing",
"Securities Brokerage",
"Junior Colleges",
"Industrial Gas Manufacturing",
"Integrated Record Production/Distribution",
"Tire and Tube Merchant Wholesalers",
"Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing",
"Wood Office Furniture Manufacturing",
"Potato Farming",
"Fire Protection",
"Administration of Education Programs",
"Men's and Boys' Cut and Sew Trouser, Slack and Jean Manufacturing",
"Discount Department Stores",
"Hydroelectric Power Generation",
"Biological Product (except Diagnostic) Manufacturing",
"Timber Tract Operations",
"Railroad Rolling Stock Manufacturing",
"Dry Pea and Bean Farming",
"Shellfish Farming",
"Motor Vehicle Metal Stamping",
"Hay Farming",
"Zoos and Botanical Gardens",
"Die-Cut Paper and Paperboard Office Supplies Manufacturing",
"Paper Industry Machinery Manufacturing",
"Enameled Iron and Metal Sanitary Ware Manufacturing",
"Printed Circuit Assembly (Electronic Assembly) Manufacturing",
"Noncellulosic Organic Fiber Manufacturing",
"Legal Counsel and Prosecution",
"Photographic Film, Paper, Plate, and Chemical Manufacturing",
"Miscellaneous Intermediation",
"Scale and Balance (except Laboratory) Manufacturing",
"Berry (except Strawberry) Farming",
"Electric Housewares and Household Fan Manufacturing",
"Dry Pasta Manufacturing",
"Broom, Brush, and Mop Manufacturing",
"Underwear and Nightwear Knitting Mills",
"Men's Footwear (except Athletic) Manufacturing",
"Lead Ore and Zinc Ore Mining",
"Air and Gas Compressor Manufacturing",
"Scheduled Passenger Air Transportation",
"Nature Parks and Other Similar Institutions",
"Marine Cargo Handling",
"Crop Harvesting, Primarily by Machine",
"Photographic Equipment and Supplies Merchant Wholesalers",
"Marking Device Manufacturing",
"Dimension Stone Mining and Quarrying",
"Line-Haul Railroads",
"Drive-In Motion Picture Theaters",
"Optical Instrument and Lens Manufacturing",
"Hat, Cap, and Millinery Manufacturing",
"Corn Farming",
"Other Footwear Manufacturing",
"Fastener, Button, Needle, and Pin Manufacturing",
"Fats and Oils Refining and Blending",
"Frozen Cakes, Pies, and Other Pastries Manufacturing",
"Other General Government Support",
"Casino Hotels",
"Rubber and Plastics Hoses and Belting Manufacturing",
"Blood and Organ Banks",
"Other Sound Recording Industries",
"Plastics Plumbing Fixture Manufacturing",
"Radio Networks",
"Grape Vineyards",
"Textile and Fabric Finishing (except Broadwoven Fabric) Mills",
"Engineered Wood Member (except Truss) Manufacturing",
"Natural Gas Liquid Extraction",
"In-Vitro Diagnostic Substance Manufacturing",
"Abrasive Product Manufacturing",
"Office Furniture (except Wood) Manufacturing",
"Urethane and Other Foam Product Manufacturing",
"Open-End Investment Funds",
"Hunting and Trapping",
"Overhead Traveling Crane, Hoist, and Monorail System Manufacturing",
"Cotton Ginning",
"Cement Manufacturing",
"Farm Labor Contractors and Crew Leaders",
"Administration of Air and Water Resource and Solid Waste Programs",
"Paper Bag and Coated and Treated Paper Manufacturing",
"Other Nonferrous Foundries (except Die-Casting)",
"Emergency and Other Relief Services",
"Household Furniture (except Wood and Metal) Manufacturing",
"Business and Secretarial Schools",
"Passenger Car Leasing",
"One-Hour Photofinishing",
"Inland Water Freight Transportation",
"Other Pressed and Blown Glass and Glassware Manufacturing",
"Cut and Sew Apparel Contractors",
"Household Vacuum Cleaner Manufacturing",
"Women's Footwear (except Athletic) Manufacturing",
"Environment, Conservation and Wildlife Organizations",
"Blankbook, Looseleaf Binders, and Devices Manufacturing",
"Unsupported Plastics Bag Manufacturing",
"Ground or Treated Mineral and Earth Manufacturing",
"Sewage Treatment Facilities",
"Search, Detection, Navigation, Guidance, Aeronautical, and Nautical Sy",
"Media Buying Agencies",
"Primary Smelting and Refining of Copper",
"Internet Service Providers",
"Unsupported Plastics Film and Sheet Manufacturing",
"Electronic Coil, Transformer, and Other Inductor Manufacturing",
"Electronic Connector Manufacturing",
"Commodity Contracts Brokerage",
"Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturin",
"Semiconductor Machinery Manufacturing",
"Copper Rolling, Drawing, and Extruding",
"Credit Bureaus",
"Industrial and Commercial Fan and Blower Manufacturing",
"Greeting Card Publishers",
"Coastal and Great Lakes Passenger Transportation",
"Pipeline Transportation of Crude Oil",
"Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment M",
"Current-Carrying Wiring Device Manufacturing",
"Metal Household Furniture Manufacturing",
"Secondary Smelting and Alloying of Aluminum",
"Iron and Steel Mills",
"Other Ordnance and Accessories Manufacturing",
"Scheduled Freight Air Transportation",
"Cattle Feedlots",
"Rope, Cordage, and Twine Mills",
"Vehicular Lighting Equipment Manufacturing",
"Wheat Farming",
"News Syndicates",
"Fiber Optic Cable Manufacturing",
"Household Laundry Equipment Manufacturing",
"Mattress Manufacturing",
"Prerecorded Compact Disc (except Software), Tape, and Record Reproduci",
"Glove and Mitten Manufacturing",
"Nonclay Refractory Manufacturing",
"Fabric Coating Mills",
"Wood Television, Radio, and Sewing Machine Cabinet Manufacturing",
"Laminated Plastics Plate, Sheet, and Shape Manufacturing",
"Totalizing Fluid Meter and Counting Device Manufacturing",
"Pulp Mills",
"Tobacco Farming",
"Ethyl Alcohol Manufacturing",
"Motor Vehicle Brake System Manufacturing",
"Storage Battery Manufacturing",
"Industrial Sand Mining",
"Industrial Process Furnace and Oven Manufacturing",
"Setup Paperboard Box Manufacturing",
"Soybean Processing",
"Rubber and Plastics Footwear Manufacturing",
"Other Hosiery and Sock Mills",
"Support Activities for Rail Transportation",
"Other Noncitrus Fruit Farming",
"Commercial Banking",
"Steel Foundries (except Investment)",
"Other Communication and Energy Wire Manufacturing",
"Women's and Girls' Cut and Sew Suit, Coat, Tailored Jacket, and Skirt",
"Rice Milling",
"Doll and Stuffed Toy Manufacturing",
"Plumbing Fixture Fitting and Trim Manufacturing",
"Jewelers' Material and Lapidary Work Manufacturing",
"Malt Manufacturing",
"Mechanical Power Transmission Equipment Manufacturing",
"Military Armored Vehicle, Tank, and Tank Component Manufacturing",
"Sheer Hosiery Mills",
"Primary Battery Manufacturing",
"International Affairs",
"Noncurrent-Carrying Wiring Device Manufacturing",
"Paperboard Mills",
"Other Chemical and Fertilizer Mineral Mining",
"Women's and Girls' Cut and Sew Blouse and Shirt Manufacturing",
"Real Estate Credit",
"Magnetic and Optical Recording Media Manufacturing",
"Regulation and Administration of Transportation Programs",
"Cigarette Manufacturing",
"Other Engine Equipment Manufacturing",
"Light Truck and Utility Vehicle Manufacturing",
"Other Animal Aquaculture",
"Copper Wire (except Mechanical) Drawing",
"Libraries and Archives",
"Breakfast Cereal Manufacturing",
"Coastal and Great Lakes FreightWater Transportation",
"Power Boiler and Heat Exchanger Manufacturing",
"Solid Waste Combustors and Incinerators",
"Men's and Boys' Neckwear Manufacturing",
"Electronics Stores",
"All Other Basic Inorganic Chemical Manufacturing",
"Other Major Household Appliance Manufacturing",
"Bituminous Coal and Lignite Surface Mining",
"Oilseed (except Soybean) Farming",
"Oilseed and Grain Combination",
"Porcelain Electrical Supply Manufacturing",
"Cellular and Other Wireless Telecommunications",
"Tree Nut Farming",
"Nonferrous (except Aluminum) Die-Casting Foundries",
"Men's and Boys' Cut and Sew Underwear and Nightwear Manufacturing",
"Aluminum Sheet, Plate, and Foil Manufacturing",
"Family Planning Centers",
"Household Refrigerator and Home Freezer Manufacturing",
"Household Cooking Appliance Manufacturing",
"Dry, Condensed, and Evaporated Dairy Product Manufacturing",
"Switchgear and Switchboard Apparatus Manufacturing",
"Creamery Butter Manufacturing",
"Computer Terminal Manufacturing",
"Other Oilseed Processing",
"Power-Driven Handtool Manufacturing",
"Electrometallurgical Ferroalloy Product Manufacturing",
"Synthetic Rubber Manufacturing",
"Spring (Light Gauge) Manufacturing",
"Other Similar Organizations (except Business, Professional, Labor, and",
"Nonwoven Fabric Mills",
"Other Depository Credit intermediation",
"On-Line Information Services",
"Securities and Commodity Exchanges",
"All Other Metal Ore Mining",
"Excavation Contractors",
"Support Activities for Nonmetallic Minerals (except Fuels)",
"Secondary Market Financing",
"Coal and Other Mineral and Ore Merchant Wholesalers",
"Irradiation Apparatus Manufacturing",
"Seafood Canning",
"Crushed and Broken Granite Mining",
"Wet Corn Milling",
"All Other Heavy Construction",
"Flour Milling",
"Brick and Structural Clay Tile Manufacturing",
"Phosphatic Fertilizer Manufacturing",
"Personal Leather Good (except Women's Handbag and Purse) Manufacturing",
"All Other Nonmetallic Mineral Mining",
"Pension Funds",
"Peanut Farming",
"Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit M",
"Voluntary Health Organizations",
"Industrial Machinery and Equipment Wholesalers",
"Petroleum Refineries",
"Offices of Bank Holding Companies",
"Strawberry Farming",
"Alumina Refining and Primary Aluminum Production",
"Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except",
"Support Activities for Coal Mining",
"Solid Waste Landfill",
"Other Knit Fabric and Lace Mills",
"Electronic Capacitor Manufacturing",
"Apple Orchards",
"Pipeline Transportation of Natural Gas",
"Health and Welfare Funds",
"Motor Vehicle Air-Conditioning Manufacturing",
"Political Organizations",
"Fur and Leather Apparel Manufacturing",
"Department Stores",
"Cotton Farming",
"Casinos (except Casino Hotels)",
"Steel Investment Foundries",
"Other Insurance Funds",
"Port and Harbor Operations",
"Mixed Mode Transit Systems",
"Motorcycle, ATV, and All Other Motor Vehicle Dealers",
"Electron Tube Manufacturing",
"Reconstituted Wood Product Manufacturing",
"Electronic Resistor Manufacturing",
"Laminated Aluminum Foil Manufacturing for Flexible Packaging Uses",
"Vitreous China Plumbing Fixture and China and Earthenware Bathroom Acc",
"Other Cut and Sew Apparel Manufacturing",
"Sugarcane Mills",
"Alumina Refining",
"Police Protection",
"Doll, Toy, and Game Manufacturing",
"All Other Pipeline Transportation",
"Cellulosic Organic Fiber Manufacturing",
"Metal Crown, Closure, and Other Metal Stamping (except Automotive)",
"Manufacturing and Industrial Building Construction",
"Carbon Paper and Inked Ribbon Manufacturing",
"Cane Sugar Refining",
"Custom Roll Forming",
"Other Gambling Industries",
"Motor Vehicle Gasoline Engine and Engine Parts Manufacturing",
"Fuel Dealers",
"Men¿s and Boys¿ Cut and Sew Apparel Manufacturing",
"Women¿s, Girls¿, and Infants¿ Cut and Sew Apparel Manufacturing",
"Other Structural Clay Product Manufacturing",
"Offices of Notaries",
"Administration of Urban Planning and Community and Rural Development",
"All Other Special Trade Contractors",
"Support Activities for Printing",
"Lime Manufacturing",
"Metal Can Manufacturing",
"Synthetic Organic Dye and Pigment Manufacturing",
"Other Grantmaking and Giving Services",
"Pipeline Transportation of Refined Patroleum Products",
"Other Motor Vehicle Parts Manufacturing",
"Industrial and Commercial Fan and Blower and Air Purification Equipmen",
"Cafeterias, Grill Buffets, and Buffets",
"Saw Blade and Handtool Manufacturing",
"Small Electrical Appliance Manufacturing",
"Computer Terminal and Other Computer Peripheral Equipment Manufacturin",
"Machine Tool Manufacturing",
"Surface Active Agent Manufacturing",
"Textile and Fabric Finishing Mills",
"Administration of Human Resource Programs (except Education, Public He",
"Regulation, Licensing, and Inspection of Miscellaneous Commercial Sect",
"Jewelry and Silverware Manufacturing",
"Nonferrous Metal (except Aluminum) Smelting and Refining",
"All Other Leather Good and Allied Product Manufacturing",
"Other Aluminum Rolling, Drawing, and Extruding",
"Gold Ore Mining",
"Sugar Beet Farming",
"Narrow Fabric Mills and Schiffli Machine Embroidery",
"Iron Ore Mining",
"Explosives Manufacturing",
"Clay Building Material and Refractories Manufacturing",
"Pottery, Ceramics, and Plumbing Fixture Manufacturing",
"Other Industrial Machinery Manufacturing",
"Textile Bag and Canvas Mills",
"Fossil Fuel Electric Power",
"Curtain and Linen Mills",
"Short Line Railroads",
"Iron and Steel Mills and Ferroalloy Manufacturing",
"Solar Electric Power Generation",
"Motor Vehicle Electrical and Electronic Equipment Manufacturing",
"Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour",
"Other Nonferrous Metal Foundries (except Die-Casting)",
"Softwood Veneer and Plywood Manufacturing",
"Stationery Product Manufacturing",
"Other Basic Inorganic Chemical Manufacturing",
"Software and Other Prerecorded Compact Disc, Tape, and Record Reproduc",
"Sawmill, Woodworking, and Paper Machinery Manufacturing",
"Fiber, Yarn, and Thread Mills",
"Civic and Social Organizations",
"Footwear Manufacturing",
"Dual-Purpose Cattle Ranching and Farming",
"Orange Groves",
"Rolling Mill and Other Metalworking Machinery Manufacturing",
"Other Justice, Public Order, and Safety Activities",
"Fruit and Tree Nut Combination",
"Gypsum Product Manufacturing",
"Other Miscellaneous Nondurable Goods Wholesalers",
"Temporary Shelters",
"Spring Manufacturing",
"Nonferrous Metal Die-Casting Foundries",
"Soybean and Other Oilseed Processing",
"Ammunition (except Small Arms) Manufacturing",
"Other Apparel Knitting Mills",
"Plumbing, Heating, and Air Conditioning Contractors",
"Tire Manufacturing (except Retreading)",
"Tobacco Manufacturing",
"Office Supplies (except Paper) Manufacturing",
"Copper Rolling, Drawing, Extruding, and Alloying",
"Corporate, Subsidiary, and Regional Managing Offices",
"Support Activities for Metal Mining",
"Wind Electric Power Generation",
"Regulation and Administration of Communications, Electric, Gas, and Ot",
"Synthetic Dye and Pigment Manufacturing",
"Anthracite Mining",
"Historical Sites",
"Artificial and Synthetic Fibers and Filaments Manufacturing",
"Religious Organizations",
"Sheep Farming",
"Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Preciou",
"Other Paperboard Container Manufacturing",
"Labor Unions and Similar Labor Organizations",
"Parole Offices and Probation Offices",
"Administration of Conservation Programs",
"Geothermal Electric Power Generation",
"Biomass Electric Power Generation",
"Convention and Visitors Bureaus",
"Phosphate Rock Mining",
"Administration of Public Health Programs",
"Newsprint Mills",
"Clay and Ceramic and Refractory Minerals Mining",
"Citrus (except Orange) Groves",
"Electric Bulk Power Transmission and Control",
"Measuring and Dispensing Pump Manufacturing",
"Rice Farming",
"Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing",
"Knit Fabric Mills",
"Other Urban Transit Systems",
"Regulation of Agricultural Marketing and Commodities",
"Electronic Shopping and Mail-Order Houses",
"Mineral Wool Manufacturing",
"Air Traffic Control",
"Cane Sugar Manufacturing",
"Hosiery and Sock Mills",
"Monetary Authorities - Central Bank",
"Motor Home Manufacturing",
"Credit Card Issuing",
"Reinsurance Carriers",
"Guided Missile and Space Vehicle Manufacturing",
"Grantmaking Foundations",
"Nuclear Electric Power Generation",
"Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills"]